# -----------------
# Main configuration for BattleTracker
#
# Documentation: https://docs.battleplugins.org/docs/bt/
# Support: https://discord.gg/tMVPVJf
# GitHub: https://github.com/BattlePlugins/BattleTracker
# -----------------
configVersion: 2.0.0

## If signs should be used.
useSigns: true

## If the number of seconds between kills is less than
## this number, show a message that the player is on a rampage.
rampageTime: 15

## Display a streak message every x kills
streakMessageEvery: 15

## Database options.
database:
  type: sqlite # sqlite or mysql
  prefix: bt_
  db: tracker # db name
  url : localhost # ignored if not mysql
  port : "3306" # ignored if not mysql
  username: root
  password: ""

## These are the default rating options, can be overridden
## by calling plugins (e.g. BattleArena)
rating:
  calculator: elo # currently just 'elo' works
  options:
    elo:
      default: 1250
      spread: 400