# plugin.yml for Bukkit, nukkit.yml overrides this if Nukkit is used instead
main: org.battleplugins.tracker.bukkit.BukkitTrackerPlugin
name: ${project.name}
api-version: 1.13
version: ${project.version}
description: ${project.description}
author: BattlePlugins
website: ${project.url}